---
- name: Install mysql
  dnf: name={{ item }} state=latest
  with_items:
    - mysql
    - mysql-server
    - mysql-devel

- name: Install PyMySQL
  pip:
    name: PyMySQL

- name: Send mysql config
  copy:
    src: my.cnf
    dest: /etc/my.cnf
  notify:
    - restart mysqld

- name: Start mysql
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create WordPress database
  mysql_db: name={{wp_db_name}} state=present

- name: Create WordPress database user
  mysql_user: name={{wp_db_user}} password={{wp_db_password}} priv={{wp_db_name}}.*:ALL host="*" state=present
