---
- name: Webserver-install
  hosts: webserver
  roles:
    - nginx
    - php-fpm
- name: DBserver-install
  hosts: dbserver
  roles:
    - python
    - mysql
- name: Wordpress-install
  hosts: webserver
  roles:
    - wordpress
