---
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
#shell: "dnf module reset -y nginx && dnf module install -y nginx:1.20"

- name: Start nginx
  service:
    name: nginx
    state: started

- name: Enable nginx
  service:
    name: nginx
    enabled: yes

- name: Send nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Send wordpress.conf
  copy:
    src: wordpress.conf
    dest: /etc/nginx/conf.d/wordpress.conf
  notify: restart nginx
#- name: restart nginx
#  service:
#    name: nginx
#   state: restarted
