---
- name: Install php-fpm
  dnf: name={{ item }} state=latest
  with_items:
    - php
    - php-fpm
    - php-mbstring
    - php-mysqlnd
    - php-json
    - php-gd

- name: start php-fpm
  service:
    name: php-fpm
    state: started
    enabled: yes

- name: Change owner
  ansible.builtin.file:
    path: /var/lib/php/session
    state: directory
    recurse: yes
    owner: nginx
    group: nginx

- name: Send www.conf
  copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
  notify: restart php-fpm
#- name: restart php-fpm
#  service:
#    name: php-fpm
#    state: restarted
